server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.1.180:3306/savesystem?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: savesystem
    password: savesystem2023@
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
mybatis:
  type-aliases-package: com.hwj.pojo
  mapper-locations: classpath:mybatis/mappers/*.xml



